# Generated by scripts/update-formula.sh from the v0.5.1 release. Do not edit.
class Shipwick < Formula
  desc "Production deployments on your own server"
  homepage "https://shipwick.com"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/shipwick/shipwick/releases/download/v0.5.1/shipwick_darwin_arm64"
      sha256 "08b7912e5d802fc40f565ff770ff652f1afd0632591ead6140358548f969d335"
    end
    on_intel do
      url "https://github.com/shipwick/shipwick/releases/download/v0.5.1/shipwick_darwin_amd64"
      sha256 "c1a6322e08705abf6d6a7944a21ad61da8ad7d30a9f8f15ca65ec38a40d12eee"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/shipwick/shipwick/releases/download/v0.5.1/shipwick_linux_arm64"
      sha256 "0ab372cdd6f103b989f4df2e1058842066fbad95b90a33003e1c990ea97289f3"
    end
    on_intel do
      url "https://github.com/shipwick/shipwick/releases/download/v0.5.1/shipwick_linux_amd64"
      sha256 "073a06120581cec89250d1b2b37cc51ecea91e947bb0896df93d059c3e91b9f1"
    end
  end

  def install
    bin.install Dir["shipwick_*"].first => "shipwick"
    # A release asset is a bare file: it arrives without the executable bit.
    chmod 0755, bin/"shipwick"
    generate_completions_from_executable(bin/"shipwick", "completion")
  end

  test do
    assert_match "shipwick version v#{version}", shell_output("#{bin}/shipwick --version")
  end
end
