# Generated by scripts/update-formula.sh from the v0.7.0 release. Do not edit.
class Shipwick < Formula
  desc "Production deployments on your own server"
  homepage "https://shipwick.com"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/shipwick/shipwick/releases/download/v0.7.0/shipwick_darwin_arm64"
      sha256 "94184a4693b6d6b2f175afeb4743b6ceb9ca1cd87f6570acfa8dda22ba3f5a24"
    end
    on_intel do
      url "https://github.com/shipwick/shipwick/releases/download/v0.7.0/shipwick_darwin_amd64"
      sha256 "4fb4363623876a0052e714072e7240d7b9da9c9944abaebe1c036c31876054e4"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/shipwick/shipwick/releases/download/v0.7.0/shipwick_linux_arm64"
      sha256 "11a001636d5de907776dd61d247769fb6100322e8727c518b9fc62364206f672"
    end
    on_intel do
      url "https://github.com/shipwick/shipwick/releases/download/v0.7.0/shipwick_linux_amd64"
      sha256 "7f59c12566f9816b0b4413803deb8bd306635e509099a9b4825464d3ff71ce4f"
    end
  end

  def install
    bin.install Dir["shipwick_*"].first => "shipwick"
    # A release asset is a bare file: it arrives without the executable bit.
    chmod 0755, bin/"shipwick"
    generate_completions_from_executable(bin/"shipwick", "completion")
  end

  test do
    assert_match "shipwick version v#{version}", shell_output("#{bin}/shipwick --version")
  end
end
