# Generated by scripts/update-formula.sh from the v0.3.0 release. Do not edit.
class Shipwick < Formula
  desc "Production deployments on your own server"
  homepage "https://shipwick.com"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/shipwick/shipwick/releases/download/v0.3.0/shipwick_darwin_arm64"
      sha256 "61f29b973d6ea0e3cab150a64ef126c75846abd6d5e5c7be5fc7d71a74c56279"
    end
    on_intel do
      url "https://github.com/shipwick/shipwick/releases/download/v0.3.0/shipwick_darwin_amd64"
      sha256 "0a7634b59cfb6c8d9c8e8a600a4179b291b667f85e0829425408d96cf2d455cd"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/shipwick/shipwick/releases/download/v0.3.0/shipwick_linux_arm64"
      sha256 "8e52bb1692cd046b89e66995c2f53eb8c596db3973a482df3b095f50a8f50e55"
    end
    on_intel do
      url "https://github.com/shipwick/shipwick/releases/download/v0.3.0/shipwick_linux_amd64"
      sha256 "609a769111fcccfccc1e129d83be5e44891cd4a99828212f3637630274a14cf9"
    end
  end

  def install
    bin.install Dir["shipwick_*"].first => "shipwick"
    # A release asset is a bare file: it arrives without the executable bit.
    chmod 0755, bin/"shipwick"
    generate_completions_from_executable(bin/"shipwick", "completion")
  end

  test do
    assert_match "shipwick version v#{version}", shell_output("#{bin}/shipwick --version")
  end
end
