#!/bin/sh
# Writes Formula/shipwick.rb for a release of shipwick/shipwick.
#
#   sh scripts/update-formula.sh            # the latest release
#   sh scripts/update-formula.sh v0.2.0     # a specific one
#
# The checksums come from the release's own checksums.txt, the same file the
# installer verifies against; nothing is downloaded and hashed here.

set -eu

REPO="shipwick/shipwick"
cd "$(dirname "$0")/.."

tag="${1:-}"
if [ -z "$tag" ]
then
  # The redirect target of /releases/latest ends in the tag.
  tag="$(curl -fsSLI -o /dev/null -w '%{url_effective}' "https://github.com/$REPO/releases/latest")"
  tag="${tag##*/}"
fi
case "$tag" in
  v[0-9]*.[0-9]*.[0-9]*) ;;
  *)
    echo "not a release tag: '$tag'" >&2
    exit 1
    ;;
esac
# Homebrew has no notion of "latest pre-release"; the tap only carries releases.
case "$tag" in *-*)
  echo "refusing a pre-release: $tag" >&2
  exit 1
  ;;
esac

base="https://github.com/$REPO/releases/download/$tag"
sums="$(curl -fsSL "$base/checksums.txt")"

sum() { # sum ASSET
  s="$(printf '%s\n' "$sums" | awk -v f="$1" '$2 == f || $2 == "*"f { print $1 }')"
  [ "${#s}" -eq 64 ] || {
    echo "checksums.txt of $tag has no entry for $1" >&2
    exit 1
  }
  printf '%s' "$s"
}

cat >Formula/shipwick.rb <<FORMULA
# Generated by scripts/update-formula.sh from the $tag release. Do not edit.
class Shipwick < Formula
  desc "Deploy Docker applications to your own server, without Kubernetes"
  homepage "https://shipwick.com"
  version "${tag#v}"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "$base/shipwick_darwin_arm64"
      sha256 "$(sum shipwick_darwin_arm64)"
    end
    on_intel do
      url "$base/shipwick_darwin_amd64"
      sha256 "$(sum shipwick_darwin_amd64)"
    end
  end

  on_linux do
    on_arm do
      url "$base/shipwick_linux_arm64"
      sha256 "$(sum shipwick_linux_arm64)"
    end
    on_intel do
      url "$base/shipwick_linux_amd64"
      sha256 "$(sum shipwick_linux_amd64)"
    end
  end

  def install
    bin.install Dir["shipwick_*"].first => "shipwick"
    # A release asset is a bare file: it arrives without the executable bit.
    chmod 0755, bin/"shipwick"
    generate_completions_from_executable(bin/"shipwick", "completion")
  end

  test do
    assert_match "shipwick version v#{version}", shell_output("#{bin}/shipwick --version")
  end
end
FORMULA

echo "Formula/shipwick.rb is at $tag"
